[package]
name = "rustsheng-core"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
authors.workspace = true

[lib]
name = "rustsheng_core"

[features]
default = ["serial", "flash-v5"]
serial = ["dep:serialport"]
flash-v5 = ["dep:aes", "dep:cbc"]

[dependencies]
thiserror.workspace = true
log.workspace = true
serialport = { workspace = true, optional = true }
aes = { workspace = true, optional = true }
cbc = { workspace = true, optional = true }
